# Site settings
title: Alyssa P. Hacker
description: Alyssa P. Hacker is a designer and developer based in San Francisco, CA.
baseurl: ""
url: ""

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
collections:
  pages:
    output: true
    permalink: /:name
  work:
    output: true
    permalink: /:name